### ISSUE TITLE
Feature Request: More languages for website

### ISSUE THREAD

**Issue by Shluffy** [theforumhelpers/theforumhelpers.github.io#124]
**Is your feature request related to a problem?**
The site only exists in english, which isn't very inclusive, especially for people that don't speak english as their language.

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

**Comment by Accio1** [comment]
@Shluffy I don't even know how this would be implemented. Scratch has a translation team of dozens of people, and they use react to generate their webpages so that the strings can be easily translated. If anyone has ideas/experience on how to translate websites, please feel free to share here. Realistically, this seems like a large undertaking for such a small site.

**Comment by leahcimto** [comment]
@Shluffy @Accio1 We don't really have the resources for this. Sure, google translate could be used but that would have a lot of errors. We would have to get people that speak multiple languages to do this and I don't really see how it's worth the effort and time for this as it is such a small website and these days almost all browsers come in with a built-in translation tool. If this were to be implemented, the only thing I see would be best would be to make a completely new repo with the same content of this repo but translated. Unless someone from the studio is willing to translate the site I don't see how this could be implemented unless we use some website translation tool, however those aren't perfect and almost all of them cost money.
