### ISSUE TITLE
Capitalisation in paths

### ISSUE THREAD

**Issue by ghost** [theforumhelpers/theforumhelpers.github.io#14]
I notice a commit stating "rename `quotes/` to `Quotes/`". It generally isn't aesthetically pleasing to use camelcase paths in URLs, nor to use underscores. I'd recommend renaming of all files back to lowercase, and using spaces (0x20 // %20) instead of underscores.

We can then address files at these locations via URI encoding (e.g. `theforumhelpers/forum%20helpers/` for the folder "forum helpers".

**Comment by Nambaseking01** [comment]
Support. 

This would make everything more organized - the current names aren't really good for web development.

**Comment by Accio1** [comment]
This will be addressed after #20 is merged.

**Comment by Accio1** [comment]
I'm going to do some more research on this, and come back with an answer when I have made a decision. Feel free to add discussion weighing the pros and cons of each method.

**Comment by Accio1** [comment]
Blocked pending site overhaul. I am leaning towards implementing this suggestion. Eg. Forum Helpers page would now be found at  https://theforumhelpers.github.io/forumhelpers/ This would make it more consistent with common site URLS.

**Comment by leahcimto** [comment]
> Blocked pending site overhaul. I am leaning towards implementing this suggestion. Eg. Forum Helpers page would now be found at https://theforumhelpers.github.io/forumhelpers/ This would make it more consistent with common site URLS.

Are we going to do /forum%20helpers or just /forumhelpers ?

**Comment by Accio1** [comment]
I'm leaning towards /forumhelpers. I personally don't like the use of %20 or other symbols in URLs. Do you agree or do you prefer /forum%20helpers ?

**Comment by leahcimto** [comment]
I like /forumhelpers too.

**Comment by leahcimto** [comment]
@Accio1 I could do this if help is wanted.

**Comment by Accio1** [comment]
Okay, I will assign you to this issue. Here is a checklist of things to change and tests

- [ ] Change folder names to reflect the new URL styles
- [ ] Change the actual relative links in each page to redirect to the page with the correct capitalization
- [ ] Do not change links to QuickReply. It is capitalized intentionally because it is the name of a specific tool (this may be changed in the future but not this update)
- [ ] Do a full run through checking each link to make sure it directs to the correct place
