### ISSUE TITLE
Documentation: Contributing.md updates

### ISSUE THREAD

**Issue by Shluffy** [theforumhelpers/theforumhelpers.github.io#240]
**What does this affect?**
Contributing.md file

**Changes/Additions**
it doesn't include anything about https://github.com/theforumhelpers/theforumhelpers.github.io/pull/226#issuecomment-860258799

**Comment by Shluffy** [comment]
@Accio1 could i pls be assigned?

**Comment by Accio1** [comment]
I think this should be left out of the contributing guidelines because this was a specific case. In certain cases, adding on to a previous PR would require a new issue to be made, whereas in this case it didn't. Since it depends on the circumstances, that would be hard to describe in a text document.
