### ISSUE TITLE
Do we need the user id?

### ISSUE THREAD

**Issue by gosoccerboy5** [theforumhelpers/theforumhelpers.github.io#261]
If we're fetching from scratchdb then we can use that to get the user id right?

**Comment by Accio1** [comment]
We currently fetch from ScratchDB to get post count. I also have it set so that there is a 1s delay between fetches so as to not spam their servers with to many consecutive requests. Therefore, it takes a while for everything to load, and loading profile pictures should (and can) be done instantly by having the user ID hard coded.

**Comment by gosoccerboy5** [comment]
wait, no. I guess the scratchdb endpoint for forums doesn't contain the user ID. I'm incredibly stupid
