### ISSUE TITLE
[Idea] add css transitions for links and edit their style

### ISSUE THREAD

**Issue by MTM828** [theforumhelpers/theforumhelpers.github.io#32]
ive noticed that they dont really blend in, especially when they're clicked. and i think the underline looks quite ugly idk.

just a small suggestion

perhaps the colour of links should be the same as the background, and on hover (add transitions so it looks way better) make it the same as the top navigation bar. and as i said remove the outlines if it looks ugly.

how will we do this?
well its done with simple css im pretty sure most of u will understand.
a {
text-decoration: none;
color: i think it was powderblue;

transition-property: color;
transition-timing-function: ease;
transition-delay: 0s;
transition-duration: 1s;
}
a:hover {
color: color of topnav
}

the code hasnt been tested so yeah

**Comment by MTM828** [comment]
um... HELLO?

**Comment by Accio1** [comment]
I don't understand what you are saying. Please provide mockup screenshots or submit a PR with your proposed changes. Also, I have a busy life right now and don't have time to reply to issues instantly. Please be patient or just @ me in the future if I haven't replied within a week instead of rudely trying to get my attention.

**Comment by MTM828** [comment]
@Accio1 ;_; All I said was "um... HELLO?". basically what im saying is that links could look better, my suggestion is that you use my css or create your own, mine is here to give you an idea, but it still could be used. <p style="font-size: 50%;">how do u del issues?</p>

**Comment by Accio1** [comment]
You can't delete issues since you aren't a repository admin. I don't really see what is wrong with the current links, so I just want you to explain a bit more what you are suggesting or give a screenshot of what you think they should look like.

**Comment by MTM828** [comment]
i just thought itd look better if you removed the underline and add transitions so it looks smoother, but i guess they look just fine. can you just delete it please? ty.

**Comment by Accio1** [comment]
Closed by request of the person who made this issue

**Comment by MTM828** [comment]
I requested it to be deleted too.

**Comment by Accio1** [comment]
I'm leaving it closed instead of deleting it in case a related issue arises it so that they can be linked.

**Comment by MTM828** [comment]
Can you delete it when the site is complete?

**Comment by MTM828** [comment]
@Accio1 ... (I know you're busy, OK?)

**Comment by MTM828** [comment]
Hey, I'm pretty sure I saw you update the site. Did you perhaps for get this issue?

**Comment by MTM828** [comment]
@Accio1 How rude. (ノಠ益ಠ)ノ

**Comment by Accio1** [comment]
Ok, I am not able to check this repository every day. Your first comment was less than a week ago so just be patient. This is borderline spam at this point so if you continue, I will block you from commenting on this repository.


> Can you delete it when the site is complete?

As for this, I don't understand what you mean. The site will never be "complete" because it will be constantly be updated in order to add improvements and new features. The issue has been closed, meaning it can't be easily accessed. Why do you want the issue to be deleted as well?

**Comment by MTM828** [comment]
@Accio1

You: "This is borderline spam at this point so if you continue, I will block you from commenting on this repository."

Can you explain how? I am very confused and further clarification would be very useful.

You: "Why do you want the issue to be deleted as well?"

Well, you (all the people who are building this site) seem to have everything under control, when I came along, I was like a fifth wheel... I'm not really interested in helping anymore as the site was half done when I wanted to join, I wasn't very familiar with the site's style, so I thought that it'd be better for you too if I quit.

And please, remember that I'm pretty new to GitHub, I have to thank you for the warning, but saying "I'll block you." ( "so if you continue, I will block you from commenting on this repository.") is just aggressive in my opinion. I also don't understand why you're slightly feeling like I'm here for trouble, you might say "I never said that, and I don't think that either.", but just listen please, the Scratch Team thing is separate, now, I prefer not to talk much about this, but I still need to clear something out: When I came here, I was happy to finally see people I can chat with, code with and have fun with, I thought I'd help you out! But you mistook it as something else (from what I can see), I can just leave you, Scratch and the Scratch Team if you want, OK? What did the Scratch Team say/do to make you think I'm bad news?
And when you reply, just please remember that I'm politely **chatting** with you, i don't like it when you reply to every sentence I write and... try to prove me wrong.

Sorry if I've done anything wrong! :(

**Comment by Accio1** [comment]
@MTM828 I've broken down your post above and given my thoughts on each major topic that you pointed out.

> @Accio1
> 
> You: "This is borderline spam at this point so if you continue, I will block you from commenting on this repository."
> 
> Can you explain how? I am very confused and further clarification would be very useful.

Constantly commenting, especially only leaving comments such as "How rude. (ノಠ益ಠ)ノ" isn't constructive. As I said in the past, I am busy and don't have time to reply to comments right away. I apologise for saying that I would block you, but I was annoyed by the amount of comments that you were leaving.

> You: "Why do you want the issue to be deleted as well?"
> 
> Well, you (all the people who are building this site) seem to have everything under control, when I came along, I was like a fifth wheel... I'm not really interested in helping anymore as the site was half done when I wanted to join, I wasn't very familiar with the site's style, so I thought that it'd be better for you too if I quit.

I'm not sure if you understand what this site is for (no offence). It will never truly be "done". The initial site was created over 2 years ago, and since then, it has had several major and minor updates. Myself and other contributors are always trying to improve the site, so we appreciate feedback like what you gave in this initial issue. Feel free to continue submitting issues and feedback. My initial review of this issue wasn't meant to be mean or discouraging. I was just having trouble visualizing what you were suggesting, so I was just asking for more information or mockups in order to help convey what you were saying

> And please, remember that I'm pretty new to GitHub, I have to thank you for the warning, but saying "I'll block you." ( "so if you continue, I will block you from commenting on this repository.") is just aggressive in my opinion. I also don't understand why you're slightly feeling like I'm here for trouble, you might say "I never said that, and I don't think that either.", but just listen please, the Scratch Team thing is separate, now, I prefer not to talk much about this, but I still need to clear something out: When I came here, I was happy to finally see people I can chat with, code with and have fun with, I thought I'd help you out! But you mistook it as something else (from what I can see), I can just leave you, Scratch and the Scratch Team if you want, OK? What did the Scratch Team say/do to make you think I'm bad news?
> And when you reply, just please remember that I'm politely **chatting** with you, i don't like it when you reply to every sentence I write and... try to prove me wrong.
> 
> Sorry if I've done anything wrong! :(

I'm not sure what you are referring to by saying "The Scratch Team Thing". The Scratch Team has not said anything to me about you that would make me thing that you are "bad news". As I said above, I think you misunderstood what I was trying to say in my reply to this issue. I love it when new people contribute ideas and suggestions to this site! I just wasn't sure exactly what you were saying so I was asking for clarification. Feel free to continue providing feedback and ideas on how this site can improve, or suggesting code snippets that you think would be effective. Additionally, my point was not to prove you wrong, just to ask about certain things that you had said. 

As far as I can tell, you have done nothing wrong aside from commenting a bit too frequently when trying to get my attention. I encourage you to continue providing feedback for this site and any other sites that you wish to provide feedback on!

Happy Holidays!
~Accio1

**Comment by MTM828** [comment]
@Accio1
I deleted the unnecessary comments I posted, I hope that helps. And sorry!

I understand that it'll never be finished, and I've created a fork to help you get what I mean too, sorry for being slightly unclear with what I'm trying to say.

The Scratch Team thing is sort of hard to explain, I think Za-Chary knows how to explain it well. And I'd like it if this issue doesn't get steered off, OK?

I guess I did something wrong, sorry. And I apologize for the misunderstandings which happened in this discussion. And I guess this really is a minor unnecessary change, and I can see why.

Good luck with the site though!
Sincerely, MTM828.
