### ISSUE TITLE
In the application instructions, it says to leave a bio on the TFH-Bios account, not using the dashboard.

### ISSUE THREAD

**Issue by penguinmoose** [theforumhelpers/theforumhelpers.github.io#343]
In the application instructions, under "I've been accepted! Now what?", it tells you to leave a bio on the TFH-Bios Scratch account. Since changing and adding bios has moved to the dashboard, I think we should change it to tell you to use the dashboard. I know that the account will tell you to use the dashboard, but it's still outdated information and might be a bit of an additional hassle.

**Comment by penguinmoose** [comment]
Also, if this gets implemented, @Accio1, can I be assigned?

**Comment by Accio1** [comment]
Good catch @penguinmoose! 

The text can probably be changed to something along the lines of:

Congratulations! You will know that you have been accepted because you will receive an invite to the studio and a comment on your profile with the good news. Within a week of your acceptance, you should gain access to [The Forum Helpers Dashboard](https://theforumhelpers.herokuapp.com/), which you can use to change your biography on [list of Forum Helpers page](https://theforumhelpers.github.io/forumhelpers/). If you have any issues with this process or questions about the dashboard, please contact either [-Accio-](https://scratch.mit.edu/users/-Accio-/) or [leahcimto](https://scratch.mit.edu/users/leahcimto/) on Scratch.

**Comment by leahcimto** [comment]
@Accio1 Maybe we can add "Please wait a week before contacting admins if you haven't received access to the dashboard yet."?

**Comment by penguinmoose** [comment]
@Accio1 That sounds great. I'll create a PR.

**Comment by penguinmoose** [comment]
@Accio1 sorry, but how do you fork the repo?

**Comment by penguinmoose** [comment]
@Accio1 Actually, I think I figured it out.

**Comment by leahcimto** [comment]
@penguinmoose Our [CONTRIBUTING.md](https://github.com/theforumhelpers/theforumhelpers.github.io/blob/master/CONTRIBUTING.md) file is very helpful if you need help with any of that :)

**Comment by penguinmoose** [comment]
@Accio1 I read that. Just found out how to fork - I might ask you some more questions if I need help

Right now I'm making the changes on my fork.

**Comment by penguinmoose** [comment]
@Accio1 I made some minor changes to your suggested text:

...biography on list of forum helpers... -> biography on **the** list of forum helpers (grammar)
Incorporating @leahcimto's suggestion, at the end of the text, I added "Please only contact admins if you haven't received access to the Dashboard for 1 week."

I made all the links in your post links.

**Comment by penguinmoose** [comment]
@Accio1 Ok, made the PR (#347) - can you take a look at it?
