### ISSUE TITLE
Bug: Labeler Occasionally not Working

### ISSUE THREAD

**Issue by leahcimto** [theforumhelpers/theforumhelpers.github.io#74]
**Describe the bug**
The auto labeler worked in the test but the last 3 pull requests I made were not auto-labeled.

**To Reproduce**
Make a Pull Request
See that it does not get auto labeled upon opening it, even if the checks pass.

**Expected behavior**
The pull request should be auto-labeled.

**Browser Information**
Mac OS Big Sur 11.1, Chrome 88.

**Additional context**
If the pull request is closed and later reopened, I think the labeler _might_ run.

**Comment by Accio1** [comment]
I noticed this also. According to the 5 minutes of research that I did, it won't label PRs that come from forks (seems weird because that is where the majority of PRs come from). If it isn't going to label PRs from forks, then I might just disable it because it seems to defeat the purpose of having a labeller if it only labels some PRs.
