### ISSUE TITLE
Feature Request: .com Domain Name (www.theforumhelpers.com)

### ISSUE THREAD

**Issue by leahcimto** [theforumhelpers/theforumhelpers.github.io#79]
Hello. I would like to purchase a .com domain for this website, so it can be located at theforumhelpers.com. After I buy it, I can simply share the domain info with you (@Accio1) and you can then add it to the site. Please let me know if you are interested.

Please note that I have zero experience with domains and have no idea how to put it on the site, I just know how to get one.

I will get one via google domains.

**Comment by leahcimto** [comment]
Alternatively, you can make me a repo admin (temporarily) and I can figure out how to configure the domain myself. Here are some instructions I got from a Scratch user:

<img width="408" alt="Screen Shot 2021-02-18 at 5 08 36 PM" src="https://user-images.githubusercontent.com/68165163/108566236-1243d280-72d4-11eb-96ee-be968b8484a2.png">

i don't exactly know what that means but i can figure it out with some youtube videos :P

**Comment by leahcimto** [comment]
bump

**Comment by leahcimto** [comment]
@Accio1 just figured out how to connect a domain. all you have to do is put the domain in the repo settings. then, it will make a CNAME file. then i can just make a CNAME file on my end and it will be connected (that is if i get the domain)

**Comment by Accio1** [comment]
@leahcimto, thanks for your initiative in order to think of ways to improve the site! However, I have a few comments about this:

1. At $12 USD per year for theforumhelpers.com, I'm not sure that it is worth the price.
2. theforumhelpers.github.io looks fine, so I'm not really sure that a new domain is needed. My guess would be that >200 people visit this site for month, so it doesn't need to have a "professional" domain for so little visitors.
3. The majority of people visiting the site would probably be doing so from the Scratch website, meaning that a new domain is not needed for SEO purposes.
4. If the domain expires, then anyone who has it bookmarked or autofilled in their search bar will be redirected to an empty URL. Or, even worse, if someone else buys the domain, they could be redirected to an entirely different site (I have seen this happen before. If a domain with enough traffic expires, then it gets "sold to the highest bidder", which can lead to 18+ content or a malicious page being displayed to anyone who visits it)! This will not happen with the .githib.io URL because it is free and therefore won't expire.

Overall, I just don't think that getting a URL is worth the time or effort. Assuming that we want to spend money on this site, it would be better suited for other purposes, such as buying server space for a small database so people can change their biographies live (not saying that is needed either, just an example), or integrating other paid services to improve the site overall.

**Comment by leahcimto** [comment]
Got it. Thanks!
