### ISSUE TITLE
Bug: Footer links are too close together

### ISSUE THREAD

**Issue by leahcimto** [theforumhelpers/theforumhelpers.github.io#89]
**Describe the bug**
The links in the footer are right on top of each other, making them hard to read.
<img width="1440" alt="Screen Shot 2021-03-07 at 7 25 11 AM" src="https://user-images.githubusercontent.com/68165163/110239718-61197b00-7f16-11eb-91ca-89e70d6bf417.png">

**To Reproduce**
Scroll down to the footer

**Expected behavior**
The links should be easy to read.

**Browser Information**
n/a

**Additional context**
This can be fixed by styling the <br> element to have a higher line-height. We could also put everything on the same line and separate things with a dot symbol (• opt+8 on mac)

**Comment by Accio1** [comment]
Somewhat related to #64 as that involves updating the header and footer to make it more accessible on mobile. This is actually an involved issue because of how the header and footer are displayed using embeds.

**Comment by gosoccerboy5** [comment]
I made a quick fix.
Basically, I removed the \<br> tags from the footer, removed the \<p> element from the footer, and wrapped the two links and "Be Moist" slogan in a div with class "**FooterDiv**". From there, I just put ```.FooterDiv {
  padding-top: 6;
}``` and I now had a centered, better spaced footer. (I'm not sure if that fix would show as well on other computers as this one.)
Unfortunately, if you're planning to do that header and footer rework anytime soon, this might be useless but then again you could still use these ideas.

**Comment by gosoccerboy5** [comment]
I can make a PR that will fix this.

**Comment by Accio1** [comment]
@gosoccerboy5 At this point, since we are no longer worried about the height of the footer, the easiest thing to do would likely just be to add a couple `<br>` tags between each line so that they are spaced out further. Also , you should just be able to set footer height to "auto" in resources/stylesheet.css to make sure that it resizes no matter how big the content is.

**Comment by gosoccerboy5** [comment]
Thanks for assigning me - should I wait until any fixes are made on PR #159, so that there won't be any conflicts?

**Comment by gosoccerboy5** [comment]
> @gosoccerboy5 At this point, since we are no longer worried about the height of the footer, the easiest thing to do would likely just be to add a couple `<br>` tags between each line so that they are spaced out further. Also , you should just be able to set footer height to "auto" in resources/stylesheet.css to make sure that it resizes no matter how big the content is.

Turns out, `<br>` tags make the footer huge.
I hate to be picky/annoying, but I think [my fix](https://github.com/gosoccerboy5/theforumhelpers.github.io/tree/fix-footer) is better. If you really want me to slap some `<br>` tags in imports.js, I can do that.
If you like, you can preview the changes you've requested at [gosoccerboy5/theforumhelpers.github.io/tree/fix-footer-take-two](https://github.com/gosoccerboy5/theforumhelpers.github.io/tree/fix-footer-take-two).
