### ISSUE TITLE
Feature Request: Replace Be Moist in the footer with a current trend

### ISSUE THREAD

**Issue by SausageMcSauce** [theforumhelpers/theforumhelpers.github.io#93]
Be Moist (currently in the footer) is not as common as it is right now, so I think it could replaced with another recent trend such as 'Be whirled' (whirl cat).

Edit: I will likely make the pull request myself.

**Comment by Accio1** [comment]
But "Be Moist" is iconic. Also, whirled cat isn't even listed as a forum trend on the Scratch Wiki, so I don't think that it is notable enough to change. If the footer trend were to be changed, it would likely be changed to one that is well known across the forums, such as the kumquats or 60 second rule posts, or ninja'd. @leahcimto thoughts?

**Comment by leahcimto** [comment]
@Accio1 @SausageMcSauce Whirl cat isn't very popular. You can see [here](https://en.scratch-wiki.info/wiki/Talk:Account_and_User_Icon_Trends) that wiki editors decided that it was not popular enough to be added. I don't think the trend is notable enough. I might be a bit bias though because I really don't like the trend.

**Comment by Accio1** [comment]
@SausageMcSauce Based on @leahcimto's response, I don't think this is something that needs to be changed. In the future, please refrain from making a PR until someone has assigned an issue to you and said that you are okay to go ahead and work on it.
