### ISSUE TITLE
Bug: labeler not labeling things with unreviewed

### ISSUE THREAD

**Issue by leahcimto** [theforumhelpers/theforumhelpers.github.io#96]
**Describe the bug**
The labeler works but it does not label things unreviewed.

**To Reproduce**
make a pr and see that it does not mark things as unreviewed.

**Expected behavior**
it should mark things as unreviewed

**Browser Information**
n/a

**Additional context**
none

**Comment by Accio1** [comment]
I've also noticed this. It was working before the most recent update so I don't know what broke. (It also seems to be removing the unreviewed label if it was added manually). I will do some research and see why this is happening. Low-prio for now because honestly the actions labeller seems to be causing more issues than it is helping resolve.
